export const routePermissionByHref: Record<string, string> = {
  "/calendar": "appointments.calendar.read",
  "/settings/team": "roles.read",
  "/settings/team/users": "users.read",
  "/settings/team/users/create": "users.create",
  "/settings/team/users/edit/:id": "users.update",
  "/settings/team/roles": "roles.read",
  "/settings/team/roles/create": "roles.create",
  "/settings/team/roles/edit/:id": "roles.update",
  "/settings/venues": "venues.read",
  "/settings/venues/create": "venues.create",
  "/settings/venues/edit/:id": "venues.update",
  "/leads": "leads.read",
  "/leads/create": "leads.create",
  "/leads/edit/:id": "leads.update",
  "/leads/:id": "leads.read",
  "/customers": "customers.read",
  "/customers/create": "customers.create",
  "/customers/edit/:id": "customers.update",
  "/customers/:id": "customers.read",
  "/appointments": "appointments.read",
  "/appointments/create": "appointments.create",
  "/appointments/edit/:id": "appointments.update",
  "/appointments/:id": "appointments.read",
};
